// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package quizimage.proxies;

public class JsonObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "QuizImage.JsonObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Text("Text"),
		Index("Index"),
		Finish_reason("Finish_reason"),
		Logprobs("Logprobs"),
		Url("Url"),
		JsonObject_Choices("QuizImage.JsonObject_Choices"),
		JsonObject_Data("QuizImage.JsonObject_Data"),
		JsonObject_Test("QuizImage.JsonObject_Test");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JsonObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected JsonObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject)
	{
		if (jsonObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, jsonObjectMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.jsonObjectMendixObject = jsonObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'JsonObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static quizimage.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return quizimage.proxies.JsonObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static quizimage.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new quizimage.proxies.JsonObject(context, mendixObject);
	}

	public static quizimage.proxies.JsonObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return quizimage.proxies.JsonObject.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Text
	 */
	public final java.lang.String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final java.lang.String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(java.lang.String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @return value of Index
	 */
	public final java.lang.Integer getIndex()
	{
		return getIndex(getContext());
	}

	/**
	 * @param context
	 * @return value of Index
	 */
	public final java.lang.Integer getIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Index.toString());
	}

	/**
	 * Set value of Index
	 * @param index
	 */
	public final void setIndex(java.lang.Integer index)
	{
		setIndex(getContext(), index);
	}

	/**
	 * Set value of Index
	 * @param context
	 * @param index
	 */
	public final void setIndex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer index)
	{
		getMendixObject().setValue(context, MemberNames.Index.toString(), index);
	}

	/**
	 * @return value of Finish_reason
	 */
	public final java.lang.String getFinish_reason()
	{
		return getFinish_reason(getContext());
	}

	/**
	 * @param context
	 * @return value of Finish_reason
	 */
	public final java.lang.String getFinish_reason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Finish_reason.toString());
	}

	/**
	 * Set value of Finish_reason
	 * @param finish_reason
	 */
	public final void setFinish_reason(java.lang.String finish_reason)
	{
		setFinish_reason(getContext(), finish_reason);
	}

	/**
	 * Set value of Finish_reason
	 * @param context
	 * @param finish_reason
	 */
	public final void setFinish_reason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String finish_reason)
	{
		getMendixObject().setValue(context, MemberNames.Finish_reason.toString(), finish_reason);
	}

	/**
	 * @return value of Logprobs
	 */
	public final java.lang.String getLogprobs()
	{
		return getLogprobs(getContext());
	}

	/**
	 * @param context
	 * @return value of Logprobs
	 */
	public final java.lang.String getLogprobs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Logprobs.toString());
	}

	/**
	 * Set value of Logprobs
	 * @param logprobs
	 */
	public final void setLogprobs(java.lang.String logprobs)
	{
		setLogprobs(getContext(), logprobs);
	}

	/**
	 * Set value of Logprobs
	 * @param context
	 * @param logprobs
	 */
	public final void setLogprobs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String logprobs)
	{
		getMendixObject().setValue(context, MemberNames.Logprobs.toString(), logprobs);
	}

	/**
	 * @return value of Url
	 */
	public final java.lang.String getUrl()
	{
		return getUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of Url
	 */
	public final java.lang.String getUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Url.toString());
	}

	/**
	 * Set value of Url
	 * @param url
	 */
	public final void setUrl(java.lang.String url)
	{
		setUrl(getContext(), url);
	}

	/**
	 * Set value of Url
	 * @param context
	 * @param url
	 */
	public final void setUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String url)
	{
		getMendixObject().setValue(context, MemberNames.Url.toString(), url);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of JsonObject_Choices
	 */
	public final quizimage.proxies.Choices getJsonObject_Choices() throws com.mendix.core.CoreException
	{
		return getJsonObject_Choices(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_Choices
	 * @throws com.mendix.core.CoreException
	 */
	public final quizimage.proxies.Choices getJsonObject_Choices(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		quizimage.proxies.Choices result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_Choices.toString());
		if (identifier != null) {
			result = quizimage.proxies.Choices.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of JsonObject_Choices
	 * @param jsonobject_choices
	 */
	public final void setJsonObject_Choices(quizimage.proxies.Choices jsonobject_choices)
	{
		setJsonObject_Choices(getContext(), jsonobject_choices);
	}

	/**
	 * Set value of JsonObject_Choices
	 * @param context
	 * @param jsonobject_choices
	 */
	public final void setJsonObject_Choices(com.mendix.systemwideinterfaces.core.IContext context, quizimage.proxies.Choices jsonobject_choices)
	{
		if (jsonobject_choices == null) {
			getMendixObject().setValue(context, MemberNames.JsonObject_Choices.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.JsonObject_Choices.toString(), jsonobject_choices.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of JsonObject_Data
	 */
	public final quizimage.proxies.Data getJsonObject_Data() throws com.mendix.core.CoreException
	{
		return getJsonObject_Data(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_Data
	 * @throws com.mendix.core.CoreException
	 */
	public final quizimage.proxies.Data getJsonObject_Data(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		quizimage.proxies.Data result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_Data.toString());
		if (identifier != null) {
			result = quizimage.proxies.Data.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of JsonObject_Data
	 * @param jsonobject_data
	 */
	public final void setJsonObject_Data(quizimage.proxies.Data jsonobject_data)
	{
		setJsonObject_Data(getContext(), jsonobject_data);
	}

	/**
	 * Set value of JsonObject_Data
	 * @param context
	 * @param jsonobject_data
	 */
	public final void setJsonObject_Data(com.mendix.systemwideinterfaces.core.IContext context, quizimage.proxies.Data jsonobject_data)
	{
		if (jsonobject_data == null) {
			getMendixObject().setValue(context, MemberNames.JsonObject_Data.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.JsonObject_Data.toString(), jsonobject_data.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of JsonObject_Test
	 */
	public final quizimage.proxies.Test getJsonObject_Test() throws com.mendix.core.CoreException
	{
		return getJsonObject_Test(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_Test
	 * @throws com.mendix.core.CoreException
	 */
	public final quizimage.proxies.Test getJsonObject_Test(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		quizimage.proxies.Test result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_Test.toString());
		if (identifier != null) {
			result = quizimage.proxies.Test.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of JsonObject_Test
	 * @param jsonobject_test
	 */
	public final void setJsonObject_Test(quizimage.proxies.Test jsonobject_test)
	{
		setJsonObject_Test(getContext(), jsonobject_test);
	}

	/**
	 * Set value of JsonObject_Test
	 * @param context
	 * @param jsonobject_test
	 */
	public final void setJsonObject_Test(com.mendix.systemwideinterfaces.core.IContext context, quizimage.proxies.Test jsonobject_test)
	{
		if (jsonobject_test == null) {
			getMendixObject().setValue(context, MemberNames.JsonObject_Test.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.JsonObject_Test.toString(), jsonobject_test.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jsonObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final quizimage.proxies.JsonObject that = (quizimage.proxies.JsonObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
