// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package quizimage.proxies;

public class Split
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject splitMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "QuizImage.Split";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Question("Question"),
		ReponseA("ReponseA"),
		ReponseB("ReponseB"),
		ReponseC("ReponseC"),
		ReponseD("ReponseD"),
		Split_JsonObject("QuizImage.Split_JsonObject"),
		Split_User_Answer("QuizImage.Split_User_Answer");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Split(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Split(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject splitMendixObject)
	{
		if (splitMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, splitMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.splitMendixObject = splitMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Split.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static quizimage.proxies.Split initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return quizimage.proxies.Split.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static quizimage.proxies.Split initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new quizimage.proxies.Split(context, mendixObject);
	}

	public static quizimage.proxies.Split load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return quizimage.proxies.Split.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Question
	 */
	public final java.lang.String getQuestion()
	{
		return getQuestion(getContext());
	}

	/**
	 * @param context
	 * @return value of Question
	 */
	public final java.lang.String getQuestion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Question.toString());
	}

	/**
	 * Set value of Question
	 * @param question
	 */
	public final void setQuestion(java.lang.String question)
	{
		setQuestion(getContext(), question);
	}

	/**
	 * Set value of Question
	 * @param context
	 * @param question
	 */
	public final void setQuestion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String question)
	{
		getMendixObject().setValue(context, MemberNames.Question.toString(), question);
	}

	/**
	 * @return value of ReponseA
	 */
	public final java.lang.String getReponseA()
	{
		return getReponseA(getContext());
	}

	/**
	 * @param context
	 * @return value of ReponseA
	 */
	public final java.lang.String getReponseA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReponseA.toString());
	}

	/**
	 * Set value of ReponseA
	 * @param reponsea
	 */
	public final void setReponseA(java.lang.String reponsea)
	{
		setReponseA(getContext(), reponsea);
	}

	/**
	 * Set value of ReponseA
	 * @param context
	 * @param reponsea
	 */
	public final void setReponseA(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reponsea)
	{
		getMendixObject().setValue(context, MemberNames.ReponseA.toString(), reponsea);
	}

	/**
	 * @return value of ReponseB
	 */
	public final java.lang.String getReponseB()
	{
		return getReponseB(getContext());
	}

	/**
	 * @param context
	 * @return value of ReponseB
	 */
	public final java.lang.String getReponseB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReponseB.toString());
	}

	/**
	 * Set value of ReponseB
	 * @param reponseb
	 */
	public final void setReponseB(java.lang.String reponseb)
	{
		setReponseB(getContext(), reponseb);
	}

	/**
	 * Set value of ReponseB
	 * @param context
	 * @param reponseb
	 */
	public final void setReponseB(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reponseb)
	{
		getMendixObject().setValue(context, MemberNames.ReponseB.toString(), reponseb);
	}

	/**
	 * @return value of ReponseC
	 */
	public final java.lang.String getReponseC()
	{
		return getReponseC(getContext());
	}

	/**
	 * @param context
	 * @return value of ReponseC
	 */
	public final java.lang.String getReponseC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReponseC.toString());
	}

	/**
	 * Set value of ReponseC
	 * @param reponsec
	 */
	public final void setReponseC(java.lang.String reponsec)
	{
		setReponseC(getContext(), reponsec);
	}

	/**
	 * Set value of ReponseC
	 * @param context
	 * @param reponsec
	 */
	public final void setReponseC(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reponsec)
	{
		getMendixObject().setValue(context, MemberNames.ReponseC.toString(), reponsec);
	}

	/**
	 * @return value of ReponseD
	 */
	public final java.lang.String getReponseD()
	{
		return getReponseD(getContext());
	}

	/**
	 * @param context
	 * @return value of ReponseD
	 */
	public final java.lang.String getReponseD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReponseD.toString());
	}

	/**
	 * Set value of ReponseD
	 * @param reponsed
	 */
	public final void setReponseD(java.lang.String reponsed)
	{
		setReponseD(getContext(), reponsed);
	}

	/**
	 * Set value of ReponseD
	 * @param context
	 * @param reponsed
	 */
	public final void setReponseD(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reponsed)
	{
		getMendixObject().setValue(context, MemberNames.ReponseD.toString(), reponsed);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Split_JsonObject
	 */
	public final quizimage.proxies.JsonObject getSplit_JsonObject() throws com.mendix.core.CoreException
	{
		return getSplit_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Split_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final quizimage.proxies.JsonObject getSplit_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		quizimage.proxies.JsonObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Split_JsonObject.toString());
		if (identifier != null) {
			result = quizimage.proxies.JsonObject.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Split_JsonObject
	 * @param split_jsonobject
	 */
	public final void setSplit_JsonObject(quizimage.proxies.JsonObject split_jsonobject)
	{
		setSplit_JsonObject(getContext(), split_jsonobject);
	}

	/**
	 * Set value of Split_JsonObject
	 * @param context
	 * @param split_jsonobject
	 */
	public final void setSplit_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, quizimage.proxies.JsonObject split_jsonobject)
	{
		if (split_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.Split_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Split_JsonObject.toString(), split_jsonobject.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Split_User_Answer
	 */
	public final quizimage.proxies.User_Answer getSplit_User_Answer() throws com.mendix.core.CoreException
	{
		return getSplit_User_Answer(getContext());
	}

	/**
	 * @param context
	 * @return value of Split_User_Answer
	 * @throws com.mendix.core.CoreException
	 */
	public final quizimage.proxies.User_Answer getSplit_User_Answer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		quizimage.proxies.User_Answer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Split_User_Answer.toString());
		if (identifier != null) {
			result = quizimage.proxies.User_Answer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Split_User_Answer
	 * @param split_user_answer
	 */
	public final void setSplit_User_Answer(quizimage.proxies.User_Answer split_user_answer)
	{
		setSplit_User_Answer(getContext(), split_user_answer);
	}

	/**
	 * Set value of Split_User_Answer
	 * @param context
	 * @param split_user_answer
	 */
	public final void setSplit_User_Answer(com.mendix.systemwideinterfaces.core.IContext context, quizimage.proxies.User_Answer split_user_answer)
	{
		if (split_user_answer == null) {
			getMendixObject().setValue(context, MemberNames.Split_User_Answer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Split_User_Answer.toString(), split_user_answer.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return splitMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final quizimage.proxies.Split that = (quizimage.proxies.Split) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
