// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package quizimage.proxies;

public class Test
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "QuizImage.Test";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Score("Score"),
		Compteur("Compteur"),
		Score_Pourcentage("Score_Pourcentage"),
		TestNumber("TestNumber"),
		Test_Account("QuizImage.Test_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Test(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Test(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testMendixObject)
	{
		if (testMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, testMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.testMendixObject = testMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Test.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static quizimage.proxies.Test initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return quizimage.proxies.Test.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static quizimage.proxies.Test initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new quizimage.proxies.Test(context, mendixObject);
	}

	public static quizimage.proxies.Test load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return quizimage.proxies.Test.initialize(context, mendixObject);
	}

	public static java.util.List<quizimage.proxies.Test> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> quizimage.proxies.Test.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Score
	 */
	public final java.lang.Integer getScore()
	{
		return getScore(getContext());
	}

	/**
	 * @param context
	 * @return value of Score
	 */
	public final java.lang.Integer getScore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Score.toString());
	}

	/**
	 * Set value of Score
	 * @param score
	 */
	public final void setScore(java.lang.Integer score)
	{
		setScore(getContext(), score);
	}

	/**
	 * Set value of Score
	 * @param context
	 * @param score
	 */
	public final void setScore(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer score)
	{
		getMendixObject().setValue(context, MemberNames.Score.toString(), score);
	}

	/**
	 * @return value of Compteur
	 */
	public final java.lang.Integer getCompteur()
	{
		return getCompteur(getContext());
	}

	/**
	 * @param context
	 * @return value of Compteur
	 */
	public final java.lang.Integer getCompteur(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Compteur.toString());
	}

	/**
	 * Set value of Compteur
	 * @param compteur
	 */
	public final void setCompteur(java.lang.Integer compteur)
	{
		setCompteur(getContext(), compteur);
	}

	/**
	 * Set value of Compteur
	 * @param context
	 * @param compteur
	 */
	public final void setCompteur(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer compteur)
	{
		getMendixObject().setValue(context, MemberNames.Compteur.toString(), compteur);
	}

	/**
	 * @return value of Score_Pourcentage
	 */
	public final java.math.BigDecimal getScore_Pourcentage()
	{
		return getScore_Pourcentage(getContext());
	}

	/**
	 * @param context
	 * @return value of Score_Pourcentage
	 */
	public final java.math.BigDecimal getScore_Pourcentage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Score_Pourcentage.toString());
	}

	/**
	 * Set value of Score_Pourcentage
	 * @param score_pourcentage
	 */
	public final void setScore_Pourcentage(java.math.BigDecimal score_pourcentage)
	{
		setScore_Pourcentage(getContext(), score_pourcentage);
	}

	/**
	 * Set value of Score_Pourcentage
	 * @param context
	 * @param score_pourcentage
	 */
	public final void setScore_Pourcentage(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal score_pourcentage)
	{
		getMendixObject().setValue(context, MemberNames.Score_Pourcentage.toString(), score_pourcentage);
	}

	/**
	 * @return value of TestNumber
	 */
	public final java.lang.Long getTestNumber()
	{
		return getTestNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of TestNumber
	 */
	public final java.lang.Long getTestNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.TestNumber.toString());
	}

	/**
	 * Set value of TestNumber
	 * @param testnumber
	 */
	public final void setTestNumber(java.lang.Long testnumber)
	{
		setTestNumber(getContext(), testnumber);
	}

	/**
	 * Set value of TestNumber
	 * @param context
	 * @param testnumber
	 */
	public final void setTestNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long testnumber)
	{
		getMendixObject().setValue(context, MemberNames.TestNumber.toString(), testnumber);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Test_Account
	 */
	public final administration.proxies.Account getTest_Account() throws com.mendix.core.CoreException
	{
		return getTest_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Test_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getTest_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Test_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Test_Account
	 * @param test_account
	 */
	public final void setTest_Account(administration.proxies.Account test_account)
	{
		setTest_Account(getContext(), test_account);
	}

	/**
	 * Set value of Test_Account
	 * @param context
	 * @param test_account
	 */
	public final void setTest_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account test_account)
	{
		if (test_account == null) {
			getMendixObject().setValue(context, MemberNames.Test_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Test_Account.toString(), test_account.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final quizimage.proxies.Test that = (quizimage.proxies.Test) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
