// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package quizimage.proxies;

public class User_Answer
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject user_AnswerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "QuizImage.User_Answer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Reponse("Reponse"),
		Split_User_Answer("QuizImage.Split_User_Answer"),
		User_Answer_Test("QuizImage.User_Answer_Test");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public User_Answer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected User_Answer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject user_AnswerMendixObject)
	{
		if (user_AnswerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, user_AnswerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.user_AnswerMendixObject = user_AnswerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'User_Answer.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static quizimage.proxies.User_Answer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return quizimage.proxies.User_Answer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static quizimage.proxies.User_Answer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new quizimage.proxies.User_Answer(context, mendixObject);
	}

	public static quizimage.proxies.User_Answer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return quizimage.proxies.User_Answer.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Reponse
	 */
	public final java.lang.String getReponse()
	{
		return getReponse(getContext());
	}

	/**
	 * @param context
	 * @return value of Reponse
	 */
	public final java.lang.String getReponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Reponse.toString());
	}

	/**
	 * Set value of Reponse
	 * @param reponse
	 */
	public final void setReponse(java.lang.String reponse)
	{
		setReponse(getContext(), reponse);
	}

	/**
	 * Set value of Reponse
	 * @param context
	 * @param reponse
	 */
	public final void setReponse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reponse)
	{
		getMendixObject().setValue(context, MemberNames.Reponse.toString(), reponse);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Split_User_Answer
	 */
	public final quizimage.proxies.Split getSplit_User_Answer() throws com.mendix.core.CoreException
	{
		return getSplit_User_Answer(getContext());
	}

	/**
	 * @param context
	 * @return value of Split_User_Answer
	 * @throws com.mendix.core.CoreException
	 */
	public final quizimage.proxies.Split getSplit_User_Answer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		quizimage.proxies.Split result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Split_User_Answer.toString());
		if (identifier != null) {
			result = quizimage.proxies.Split.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Split_User_Answer
	 * @param split_user_answer
	 */
	public final void setSplit_User_Answer(quizimage.proxies.Split split_user_answer)
	{
		setSplit_User_Answer(getContext(), split_user_answer);
	}

	/**
	 * Set value of Split_User_Answer
	 * @param context
	 * @param split_user_answer
	 */
	public final void setSplit_User_Answer(com.mendix.systemwideinterfaces.core.IContext context, quizimage.proxies.Split split_user_answer)
	{
		if (split_user_answer == null) {
			getMendixObject().setValue(context, MemberNames.Split_User_Answer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Split_User_Answer.toString(), split_user_answer.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of User_Answer_Test
	 */
	public final quizimage.proxies.Test getUser_Answer_Test() throws com.mendix.core.CoreException
	{
		return getUser_Answer_Test(getContext());
	}

	/**
	 * @param context
	 * @return value of User_Answer_Test
	 * @throws com.mendix.core.CoreException
	 */
	public final quizimage.proxies.Test getUser_Answer_Test(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		quizimage.proxies.Test result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.User_Answer_Test.toString());
		if (identifier != null) {
			result = quizimage.proxies.Test.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of User_Answer_Test
	 * @param user_answer_test
	 */
	public final void setUser_Answer_Test(quizimage.proxies.Test user_answer_test)
	{
		setUser_Answer_Test(getContext(), user_answer_test);
	}

	/**
	 * Set value of User_Answer_Test
	 * @param context
	 * @param user_answer_test
	 */
	public final void setUser_Answer_Test(com.mendix.systemwideinterfaces.core.IContext context, quizimage.proxies.Test user_answer_test)
	{
		if (user_answer_test == null) {
			getMendixObject().setValue(context, MemberNames.User_Answer_Test.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.User_Answer_Test.toString(), user_answer_test.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return user_AnswerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final quizimage.proxies.User_Answer that = (quizimage.proxies.User_Answer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
